name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "Maintenance"
    labels:
      - "chore"
      - "maintenance"
      - "dependencies"
  - title: "Documentation"
    labels:
      - "documentation"
      - "docs"
change-template: "- $TITLE (#$NUMBER)"
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
template: |
  ## What's Changed

  $CHANGES
exclude-labels:
  - "skip-changelog"
  - "released"
autolabeler:
  - label: "chore"
    branch:
      - '/chore\/.+/'
  - label: "bug"
    branch:
      - '/fix\/.+/'
  - label: "enhancement"
    branch:
      - '/feature\/.+/'
  - label: "documentation"
    branch:
      - '/docs\/.+/'
