name: Bug report
description: Report a bug to help us improve
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug.
  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      options:
        - label: I have searched existing issues
          required: true
        - label: I can reproduce this with the latest version
          required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear description of what the bug is.
      placeholder: What happened? What did you expect?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the behavior.
      placeholder: |
        1. Configure damage-control.json with ...
        2. Run command ...
        3. Expected: ...
        4. Actual: ...
  - type: input
    id: version
    attributes:
      label: Plugin version
      placeholder: e.g., 1.3.0
    validations:
      required: true
  - type: input
    id: opencode_version
    attributes:
      label: OpenCode version
      placeholder: e.g., 0.1.0
  - type: input
    id: node_version
    attributes:
      label: Node.js version
      placeholder: e.g., 22.0.0
  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: e.g., macOS 15.5, Ubuntu 24.04
  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Your damage-control.json (if customized)
      render: json
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Relevant error messages or output
      render: shell
